language: python
python:
  - "2.7"
before_install:
 - sudo add-apt-repository -y ppa:pyside/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-pyside
 - export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages/"
# command to run tests
script: python -m unittest discover -s tests
